### PR TITLE
Remove usage of $php_errormsg

### LINKED ISSUE #35: php 8: The track_errors ini directive has been removed
The track_errors ini directive has been removed. This means that php_errormsg is no longer available. The error_get_last() function may be used instead.

- https://www.php.net/manual/en/migration80.incompatible.php

### PR DESCRIPTION
**Pull request by Megatherium**
The track_errors directive and the global $php_errormsg variable have been removed in PHP8. The same functionality can be achieved via error_get_last() thereby making the framework compatible with PHP8 in this respect.

closes #35

### CODE REVIEW

**Comment by glensc** [comment]
Version info:
- https://www.php.net/error_get_last

(PHP 5 >= 5.2.0, PHP 7)

**Comment by glensc** [comment]
typo in commit message: `beeb`

**Comment by glensc** [comment]
@Megatherium there is some side effect on this, `$php_errormsg` is local to function/method, but `error_get_last()` is global, so if previous code was able to check `$php_errormsg` if error has happened, then in new code, `error_get_last()` must be called only if it is certain that error has occoured.

have you considered this in the changes you made?

there is [error_clear_last()](https://www.php.net/manual/en/function.error-clear-last.php), but that's php7, but there's polyfill for that:
- https://github.com/symfony/polyfill-php70

we would not need that error clearing method if the "use error_get_last() only on errors" principle is followed.

**Comment by glensc** [comment]
@Megatherium there are some totally new tests added with this PR. where they originate from? perhaps submit them as separate PR and leave credits/info?

**Comment by glensc** [comment]
@Megatherium also, please rebase your branch against current `master`.

**Comment by Megatherium** [comment]
> have you considered this in the changes you made?

No, I was unaware of this distinction. I will look into it.

>there are some totally new tests added with this PR. where they originate from?

I added them. I assume to test my changes but it's been a while...

>please rebase your branch against current `master`. this is to ensure CI stays green even after the merge.

Will try.

**Comment by glensc** [comment]
> > there are some totally new tests added with this PR. where they originate from?
> 
> I added them. I assume to test my changes but it's been a while...

Ah okay, It's okay then

**Comment by glensc** [comment]
@Megatherium @falkenhawk please add "closes https://github.com/zf1s/zf1/issues/35" to PR body. I don't have administrative privileges to do so myself.

**Comment by glensc** [comment]
@marcing you need to add "symfony/polyfill-php70" to each subpackage `composer.json`, where you used `error_clear_last()`.

**Comment by Megatherium** [comment]
> @Megatherium you need to add "symfony/polyfill-php70" to each subpackage `composer.json`, where you used `error_clear_last()`.

Done.

Also: 5.3 and 5.4 finish flawlessly over on Travis. Github seems to have mangled their images.

**Comment by glensc** [comment]
Reported about ext-ldap again:
- https://github.com/shivammathur/setup-php/issues/407

**Comment by glensc** [comment]
@Megatherium so here's an example that I had in mind. this code block does not need error_clear_last(), as the error_get_last() is called only if the error happens.

```php
        error_clear_last();
        $feed = @file_get_contents($filename);
        if ($feed === false) {
            /**
             * @see Zend_Feed_Exception
             */
            $err = error_get_last();
            $phpErrormsg = isset($err['message'][0]) ? $err['message'] : null;
            throw new Zend_Feed_Exception("File could not be loaded: $phpErrormsg");
        }
        return self::importString($feed);
```

But as the new dependency was introduced, I guess it's best to just call it anyay, to be sure the code doesn't break on future code changes.

**Review by glensc — APPROVED** [review]

**Comment by glensc** [comment]
@Megatherium can you re-run the CI, as it seems to be a temporary issue:
- https://github.com/shivammathur/setup-php/issues/407#issuecomment-773640519

**Comment by Megatherium** [comment]
FYI The last commit just contained an extra blank like to trigger the CI.

**Review by falkenhawk — APPROVED** [review]
Thank you very much for your ongoing commitment @Megatherium and @glensc!

**Comment by falkenhawk** [comment]
oh. perhaps I should have merged https://github.com/zf1s/zf1/pull/32 first 🙈

**Comment by glensc** [comment]
> FYI The last commit just contained an extra blank like to trigger the CI.

1. you don't need to commit. there's re-run all jobs in actions web ui
2. you can also `git commit --amend && git push --force-with-lease`, which is sufficient if the commit date changes to make a new commit hash.

**Comment by glensc** [comment]
> oh. perhaps I should have waited for #32 to be merged first 🙈

these are standalone changesets. The problem with #32 is that it's a too big bite to take a time, and is still not reviewed/merged.

I thought to extract changes from there into separate PR if I have time, but apparently, I don't.

**Comment by Megatherium** [comment]
> > FYI The last commit just contained an extra blank like to trigger the CI.
> 
>     1. you don't need to commit. there's re-run all jobs in actions web ui

True but not for me on this repo. Probably a rights thing.

>     2. you can also `git commit --amend && git push --force-with-lease`, which is sufficient if the commit date changes to make a new commit hash.

Good to know.

**Comment by glensc** [comment]
> > 1. you don't need to commit. there's re-run all jobs in actions web ui
> 
> True but not for me on this repo. Probably a rights thing.

You need to go to your fork Actions tab. jobs from there are retry-able.

**Pull request merged**
