### PR TITLE
CI: Enable php 8.1/8.2 experimental

### PR DESCRIPTION
**Pull request by glensc**
Just to have 8.1/8.2 running in CI

### CODE REVIEW

**Comment by glensc** [comment]
The first task is to make phpunit compatible:

```
Run vendor/bin/phpunit --verbose || $FAILURE_ACTION
PHP Fatal error:  Cannot acquire reference to $GLOBALS in /home/runner/work/zf1/zf1/vendor/zf1s/phpunit/PHPUnit/Util/Configuration.php on line 541
```

- https://github.com/zf1s/zf1/actions/runs/3176955985/jobs/5176847025

**Comment by glensc** [comment]
It seems to be worked on already:
- https://github.com/zf1s/phpunit/pull/5

**Comment by falkenhawk** [comment]
https://github.com/zf1s/phpunit/pull/9 has been merged.
@glensc will you switch to https://github.com/zf1s/phpunit/releases/tag/3.7.41 here please? You may also enable 8.2 in gha at the same time, just to have it already running.

**Comment by glensc** [comment]
CI green (can be merged), but tests don't pass (as expected):
- 8.1: https://github.com/zf1s/zf1/actions/runs/3227106631/jobs/5281470110
- 8.2: https://github.com/zf1s/zf1/actions/runs/3227106631/jobs/5281470236

**Review by falkenhawk — APPROVED** [review]
cool, thanks!

**Pull request merged**
