### PR TITLE
Release 1.13.4 notes

### PR DESCRIPTION
**Pull request by glensc**
cc @falkenhawk

### CODE REVIEW

**Comment by glensc** [comment]
the changelog entries are taken from merge commits. so please edit (future) merge request titles before merge so the fit properly as a changelog entry.

**Comment by glensc** [comment]
@falkenhawk merge please

**Comment by falkenhawk** [comment]
@glensc I'd prefer not to release 'partially-compatible php8 version' yet, but include https://github.com/zf1s/zf1/pull/32, if you don't mind. 🙏

**Comment by glensc** [comment]
I don't mind if you cherry-pick to preserve authorship. 

Or take over this PR and add your commits on top of it when releasing.

**Comment by glensc** [comment]
I can also remove the last commit, so you can merge the first two commits.

**Comment by falkenhawk** [comment]
1.13.4 released in https://github.com/zf1s/zf1/commit/8e1040b4a5c147f8751994a597253d9c460b10cd.

**Comment by glensc** [comment]
no authorship was preserved :(

**Pull request closed without merging**
