### PR TITLE
Reduce redundant else-branching (after throws), add missing @throws annotations

### PR DESCRIPTION
**Pull request by glensc**
Carry https://github.com/Shardj/zf1-future/pull/104.

- Excluded whitespace and formatting changes.
- Included extra fixes:
   - https://github.com/Shardj/zf1-future/pull/104/files#r992515043
   - https://github.com/Shardj/zf1-future/pull/104/files#r992486395
   
cc @kstenschke

### CODE REVIEW

**Comment by glensc** [comment]
php 8.0 job needs retry. i don't have permission to do so myself. some temporary error setting up container.

**Comment by falkenhawk** [comment]
@glensc `@throws` tags are useful indeed.

But do we really need all the code beautifying? let the zf1 be the ugly beast, only taming it to make it work without errors on newer php versions. I don't want to follow others path trying to make the codebase look cleaner or more modern :)

**Comment by falkenhawk** [comment]
or is it a matter of a IDE complaining there, for redundant `else` after `return`, when using zf1 in a project?

**Comment by glensc** [comment]
I already excluded whitespace and formatting changes (if you open the original pull request), which makes merging the codebase more difficult again, but at least `diff -w` might help (haven't tested)

**Comment by glensc** [comment]
Extracted annotations:
- https://github.com/zf1s/zf1/pull/140

so you can decide about the other changes later.

**Comment by falkenhawk** [comment]
Oh that's lovely, thanks @glensc . I will look into it

**Comment by falkenhawk** [comment]
decided to go with #140 instead

**Pull request closed without merging**
