### PR TITLE
CI: Switch to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by glensc**
refs:
- https://github.com/zf1s/zf1/pull/93#issuecomment-896655753

cc @falkenhawk

### CODE REVIEW

**Comment by glensc** [comment]
The ubuntu-16.04 was added in 0bd7eea1c94cc2f2527f93ec94cedefe133cf933 via #72.

Since it's no longer available, we can't use it anymore.

**Comment by glensc** [comment]
Oh. damn. now we have CI failures for 5.3, 5.4, 5.5

has the upstream PHP image changed? seems the XML library errors differ:
- https://github.com/zf1s/zf1/runs/3299552307

```
There were 5 failures:

1) Zend_Translate_Adapter_QtTest::testCreate
Failed asserting that 'XML error: mismatched tag at line 13 of file /home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/_files/failed.ts' contains "Mismatched tag at line".

/home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/QtTest.php:65

2) Zend_Translate_Adapter_TbxTest::testCreate
Failed asserting that 'XML error: mismatched tag at line 7 of file /home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/_files/failed.tbx' contains "Mismatched tag at line".

/home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/TbxTest.php:65

3) Zend_Translate_Adapter_TmxTest::testCreate
Failed asserting that 'XML error: mismatched tag at line 10 of file /home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/_files/failed.tmx' contains "Mismatched tag at line".

/home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/TmxTest.php:65

4) Zend_Translate_Adapter_XliffTest::testCreate
Failed asserting that 'XML error: mismatched tag at line 8 of file /home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/_files/failed.xliff' contains "Mismatched tag at line".

/home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/XliffTest.php:65

5) Zend_Translate_Adapter_XmlTmTest::testCreate
Failed asserting that 'XML error: mismatched tag at line 8 of file /home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/_files/failed.xmltm' contains "Mismatched tag at line".

/home/runner/work/zf1/zf1/tests/Zend/Translate/Adapter/XmlTmTest.php:65
```

**Comment by falkenhawk** [comment]
just fyi, I tried to use https://github.com/nektos/act to run GHA locally for in-place debugging, but it fails to setup php 5.3/5.5... I tried the following docker images for the runner:
- `nektos/act-environments-ubuntu:18.04` (defined as `large` in `act`)
```
[Tests/PHP 5.5]   �  docker exec cmd=[node /var/run/act/actions/shivammathur-setup-php@v2/dist/index.js] user=
| [command]/bin/bash /opt/hostedtoolcache/linux.sh 5.5 /run/act/actions/shivammathur-setup-php@v2/dist
|
| ==> Setup PHP
| ✗ PHP Could not setup PHP 5.5
[Tests/PHP 5.5]   ❗  ::error::The process '/bin/bash' failed with exit code 1
[Tests/PHP 5.5]   ❌  Failure - Setup PHP ${{ matrix.php }}
```
- `catthehacker/ubuntu:act-20.04` (defined as `medium` in `act`)
```
[Tests/PHP 5.5]   �  docker exec cmd=[node /var/run/act/actions/shivammathur-setup-php@v2/dist/index.js] user=
| [command]/usr/bin/bash /opt/hostedtoolcache/linux.sh 5.5 /run/act/actions/shivammathur-setup-php@v2/dist
|
| ==> Setup PHP
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
[Tests/PHP 5.5]   ⚙  ::set-output:: php-version=
| ✓ PHP Installed PHP
|
| ==> Setup Tools
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| ✓ composer Added composer 2.1.5
| ✓ cs2pr Added cs2pr
|
| ==> Setup Extensions
| php: error while loading shared libraries: libaspell.so.15: cannot open shared object file: No such file or directory
| /run/act/actions/shivammathur-setup-php@v2/dist/../src/scripts/common.sh: line 131: ext_dir: parameter null or not set
[Tests/PHP 5.5]   ❗  ::error::The process '/usr/bin/bash' failed with exit code 1
[Tests/PHP 5.5]   ❌  Failure - Setup PHP ${{ matrix.php }}
```
- `catthehacker/ubuntu:act-18.04` (same results as above)

**Comment by falkenhawk** [comment]
@glensc nvm the comment above, now I realized I should use docker images provided by the creator of setup-php, as specified in https://github.com/shivammathur/setup-php#local-testing-setup

**Comment by glensc** [comment]
@falkenhawk the way I see it, is that error messages differ, because likely updated libxml, so the unit tests need to be updated to accept old/new forms.

**Comment by falkenhawk** [comment]
using `act -P ubuntu-20.04=shivammathur/node:2004`
```
| [command]/usr/bin/bash /opt/hostedtoolcache/linux.sh 5.5 /run/act/actions/shivammathur-setup-php@v2/dist
| ✗ PHP PHP 5.5 is not supported on self-hosted runner
[Tests/PHP 5.5]   ❗  ::error::The process '/usr/bin/bash' failed with exit code 1
[Tests/PHP 5.5]   ❌  Failure - Setup PHP ${{ matrix.php }}
```
🙈

**Comment by glensc** [comment]
@falkenhawk once you get it running GHA locally, it would be nice, if you document it into CONTRIBUTING.md or README.md

**Review by falkenhawk — APPROVED** [review]

**Pull request merged**
