### PR TITLE
Convert all *.php files to Unix line encoding

### PR DESCRIPTION
**Pull request by glensc**
Required to solve syntax error in one of these files:
- https://github.com/zf1s/zf1/pull/37#issuecomment-740449838

```
git ls-files '**/*.php' | xargs dos2unix
```

### CODE REVIEW

**Comment by glensc** [comment]
Had real trouble fixing the syntax error as could not find an editor that would not try to convert file encoding when making a single line change.

In vim 'set bin' finally helped, but I think the file encodings should be unified really.

**Comment by glensc** [comment]
cc @falkenhawk 

not sure should I ping you in MR's or you have all notifications enabled in this repository.

**Comment by falkenhawk** [comment]
I have all notifications enabled.
Thank you for yet another PR!

**Review by falkenhawk — APPROVED** [review]

**Comment by glensc** [comment]
@falkenhawk ok great, I'll not bother pinging you separately then. If PR is not in draft state, it's ready to be merged if it's ok for you too.

**Pull request merged**
