### PR TITLE
Replace Travis with GitHub Actions

### PR DESCRIPTION
**Pull request by glensc**
- [x] GHA Jobs not appearing under Checks. Probably needs to be merged to `master` first.
- [x] [Zend_Ldap_ConverterTest::testToLdapSerialize](https://github.com/zf1s/zf1/pull/34#issuecomment-737771053): Fixed by using `CI` instead of `TRAVIS` env
- [ ] [Zend_Db_Table_Select_MysqliTest::testSelectWhereWithTypeFloat
Zend_Db_Select::_join(): Error occurred while closing statement](https://github.com/zf1s/zf1/pull/34#issuecomment-737886457)
- [ ] [Zend_Locale_FormatTest::testToFloatSetlocale](https://github.com/zf1s/zf1/pull/34#issuecomment-739896070)

### CODE REVIEW

**Comment by glensc** [comment]
@falkenhawk can you check if GitHub Actions need to be enabled for this to work?

**Comment by falkenhawk** [comment]
hi Elan, I don't see any option to enable for gha to run here. Perhaps there is a setting to toggle on your fork?
Or try with `pull_request_target` maybe? https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

Do you think there might be a chance to have GHA running for full range 5.3-8.0 of php versions, as it was on travis?

**Comment by glensc** [comment]
```
1) Zend_Ldap_ConverterTest::testToLdapSerialize with data set #2 ('O:8:"DateTime":3:{s:4:"date";s:19:"1970-01-01 00:00:00";s:13:"timezone_type";i:1;s:8:"timezone";s:6:"+00:00";}', DateTime)
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'O:8:"DateTime":3:{s:4:"date";s:19:"1970-01-01 00:00:00";s:13:"timezone_type";i:1;s:8:"timezone";s:6:"+00:00";}'
+'O:8:"DateTime":3:{s:4:"date";s:26:"1970-01-01 00:00:00.000000";s:13:"timezone_type";i:1;s:8:"timezone";s:6:"+00:00";}'
```

- 5.5: https://github.com/glensc/php-zf1s/runs/1491536496?check_suite_focus=true
- 5.4: https://github.com/glensc/php-zf1s/runs/1491536480?check_suite_focus=true

I wonder, is it related to some php.ini setting?

**Comment by glensc** [comment]
@falkenhawk do you have a list of PHP extensions needed for the test suite? from Travis config I see `memcache`, `memcached`, and `ldap` are added, but no info about other already present extensions.

**Comment by glensc** [comment]
`Zend_Ldap_ConverterTest::testToLdapSerialize` uses [serialize](https://www.php.net/serialize) :

- https://github.com/zf1s/zf1/blob/1.13.4/packages/zend-ldap/library/Zend/Ldap/Converter.php#L213

**Comment by glensc** [comment]
Seems `Zend_Ldap_ConverterTest::testToLdapSerialize` was already broken, just earlier skipped with `TRAVIS` env, need to change those to `CI` env check. 

- https://github.com/zf1s/zf1/blob/1.13.4/tests/Zend/Ldap/ConverterTest.php#L124

eventually, remove the Travis specific exceptions, perhaps the input data could be all set same for all versions. but I'm leaving out that for now out of this PR.

**Comment by glensc** [comment]
any ideas on this one?

```
1) Zend_Db_Table_Select_MysqliTest::testSelectWhereWithTypeFloat
Zend_Db_Select::_join(): Error occurred while closing statement
```

happens with 5.5 and 5.4 only:
- https://github.com/glensc/php-zf1s/runs/1491945187?check_suite_focus=true

**Comment by glensc** [comment]
> 1) Zend_Db_Table_Select_MysqliTest::testSelectWhereWithTypeFloat
> Zend_Db_Select::_join(): Error occurred while closing statement

this makes no sense:
- https://github.com/zf1s/zf1/blob/8e1040b4a5c147f8751994a597253d9c460b10cd/packages/zend-db/library/Zend/Db/Select.php#L852

how can array value assignment produce such error? all the values are variables, no function calls:

```php
            $this->_parts[self::FROM][$correlationName] = array(
                'joinType'      => $type,
                'schema'        => $schema,
                'tableName'     => $tableName,
                'joinCondition' => $cond
                );
```

I can not find any match for such error message in zf1s codebase...

**Comment by glensc** [comment]
Seems the error comes from ext/mysqli:
- https://github.com/php/php-src/blob/php-5.4.45/ext/mysqli/mysqli.c#L165

@falkenhawk what can we do here with that?

**Comment by glensc** [comment]
```
1) Zend_Locale_FormatTest::testToFloatSetlocale
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1 234,50'
+'123 4,5,00'

/home/runner/work/php-zf1s/php-zf1s/tests/Zend/Locale/FormatTest.php:947
```

locale test goes totally bizarre after installing required locales. note two commas in value!

the input number is `$myFloat = 1234.5;`

it fails in all PHP versions except 7.4!

- https://github.com/glensc/php-zf1s/runs/1509613347?check_suite_focus=true
- https://github.com/zf1s/zf1/blob/1.13.4/tests/Zend/Locale/FormatTest.php#L947

**Comment by glensc** [comment]
seems enabling locale tests by installing needed locales, brings more trouble than needed.

the tests are not run in proper isolation, i.e global resource like locale must be restored after a test, and that is not performed, neither are tests run in isolation (i think phpunit 3.7 does not even support that), and sql queries are written with very bad style, resulting syntax error as numeric value value formatted with comma according to locale rules, gets parsed as two values in sql.

```
2) Zend_Db_Table_Select_MysqliTest::testSelectWhereOr
Zend_Db_Exception: SQL error for "INSERT INTO `zfprice` (`product_id`, `price_name`, `price_total`) VALUES (1, 'Price 1', 200,45)": Column count doesn't match value count at row 1
```

- https://github.com/glensc/php-zf1s/runs/1510708630?check_suite_focus=true

**Comment by glensc** [comment]
here's some command to give an idea of extensions needed

```
$ git grep extension_loaded|grep tests|sed -re 's/.*extension_loaded([^)]+).*/\1/'|sort -u
($ext[$driver]
('apc'
('bcmath'
('bz2'
('curl'
('fileinfo'
('gd'
('gmp'
('igbinary'
('json'
('ldap'
('lzf'
('mbstring'
('mcrypt'
('memcache'
('memcached'
('oci8'
('openssl'
('pdo'
('pdo_sqlite'
('rar'
('soap'
('sqlite'
('wddx'
('wincache'
('xcache'
('xdebug'
('zip'
('zlib'
```

**Comment by glensc** [comment]
@falkenhawk what you think of setting up the GHA incrementally, like adding each new extension brings up tons of issues whose resolving takes an undefined amount of time. I'm still struggling with locale errors as you can see from the commit noise.

Perhaps keep Travis enabled in parallel until you're satisfied with the GHA result?

ps: https://github.com/zf1s/zf1/pull/36 and https://github.com/zf1s/zf1/pull/37 depending on the former already created

**Comment by glensc** [comment]
ext-memcached is broken for 5.3:
- https://github.com/shivammathur/setup-php/issues/358

**Comment by glensc** [comment]
more bizarrre failures. how can Zend_Db_Table_Select_Pdo_SqliteTest::testSelectWhereOr end up loading controller templates?!

```
2020-12-07T20:15:53.2459221Z 2) Zend_Db_Table_Select_Pdo_SqliteTest::testSelectWhereOr
2020-12-07T20:15:53.2461077Z PHPUnit_Framework_Exception: PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/runner/work/php-zf1s/php-zf1s/tests/Zend/Controller/_files/modules/foo/views/scripts/admin/index/use-helper.phtml:1
2020-12-07T20:15:53.2462240Z Stack trace:
2020-12-07T20:15:53.2462712Z #0 Standard input code(2295): require_once()
2020-12-07T20:15:53.2463149Z #1 {main}
2020-12-07T20:15:53.2464239Z   thrown in /home/runner/work/php-zf1s/php-zf1s/tests/Zend/Controller/_files/modules/foo/views/scripts/admin/index/use-helper.phtml on line 1
2020-12-07T20:15:53.2464975Z
2020-12-07T20:15:53.2466484Z Fatal error: Uncaught Error: Using $this when not in object context in /home/runner/work/php-zf1s/php-zf1s/tests/Zend/Controller/_files/modules/foo/views/scripts/admin/index/use-helper.phtml on line 1
2020-12-07T20:15:53.2478035Z
2020-12-07T20:15:53.2479467Z Error: Using $this when not in object context in /home/runner/work/php-zf1s/php-zf1s/tests/Zend/Controller/_files/modules/foo/views/scripts/admin/index/use-helper.phtml on line 1
2020-12-07T20:15:53.2480459Z
2020-12-07T20:15:53.2480801Z Call Stack:
2020-12-07T20:15:53.2481237Z     0.0029    1268576   1. {main}() Standard input code:0
2020-12-07T20:15:53.2482742Z     0.4459  101703584   2. require_once('/home/runner/work/php-zf1s/php-zf1s/tests/Zend/Controller/_files/modules/foo/views/scripts/admin/index/use-helper.phtml') Standard input code:2295
2020-12-07T20:15:53.2483574Z
2020-12-07T20:15:53.2483770Z
```

- https://github.com/glensc/php-zf1s/runs/1513146973?check_suite_focus=true

ps: use download logs, scrolling them in browser is not something i'd recommend

**Comment by falkenhawk** [comment]
Whoa that's some struggle here. You are doing a tremendous job @glensc thank you!

I am sorry I cannot be of much help here as I am currently busy with other work-related stuff...
`Perhaps keep Travis enabled in parallel until you're satisfied with the GHA result?` yes let's still have travis running (as long as it works, but who knows for how long - I can sense some bad vibes since they were aquired by another company - it looks like they are on a downward spiral only to be shut down at some point soon) - until the point we are satisfied with the GHA result, but please continue on this PR as long as you have resources for it and feel that motivation 🙈

How come Travis had not been throwing such errors before 🤔 (locale, db, etc.)

**Comment by glensc** [comment]
My guess why Travis did not fail on these, as those tests were skipped.

The `ext/mysqli` failure, is my guess that 5.4 and 5.5 have some bug, which did not manifest on Travis built PHP (different OS, different compiler) but could be that maybe `ext/mysqli` tests were not ran in Travis.

_I've also felt Travis downfall, in projects I was forced to switch to GHA because Travis's pipeline was in the queue for days, which is not acceptable. And at some point the Travis integration was not visible in GitHub at all, had to contact Travis support, and they said I need to remove the token and setup Integration again._

**Comment by falkenhawk** [comment]
Current status - travis: (php 8.0)
```
OK, but incomplete or skipped tests!

Tests: 15522, Assertions: 61406, Incomplete: 22, Skipped: 607.
```

GHA: (php 8.0)
```
OK, but incomplete or skipped tests!
Tests: 15572, Assertions: 61706, Incomplete: 21, Skipped: 586.
```

There are even less tests skipped on GHA compared to travis. 🎉
Thank you @glensc for your excellent work here. It would not be possible without your contributions!

So I think the migration can be considered as complete now and travis config can be deleted?

**Comment by glensc** [comment]
@falkenhawk thanks for your kind words. yes, Travis can be deleted.

not sure about this PR in particular, here may be some changes that haven't been extracted to separate PR. This PR itself is not mergeable, and rebase is not worthy of it. but could do another merge commit here and see what changes remained.

**Comment by glensc** [comment]
From the top of my head I recall problematic were MySQL, locale tests. Actually locale tests are GHA only, they were not properly done in Travis.

I think memcache and pgsql may be still missing from GitHub Actions.

**Comment by glensc** [comment]
Merged changes from origin/master. Some changes remaining, if you wish you could cherry-pick them. But seems mostly those are just because the changes extracted here were solved differently after review. And some spelling fixes and missing properties are not that important.

**Pull request closed without merging**
