### PR TITLE
fixed Zend_Validate_Barcode_IntelligentMail class name for psr-0 auto…

### PR DESCRIPTION
**Pull request by marcing**
…loading compatibility

### CODE REVIEW

**Comment by falkenhawk** [comment]
@marcing I wonder if it would make more sense to rename the file instead? 🤔

**Comment by falkenhawk** [comment]
@marcing a test is failing
```
1) Zend_Validate_BarcodeTest::testINTELLIGENTMAIL

include_once(Intelligentmail.php): failed to open stream: No such file or directory
/home/travis/build/zf1s/zf1/packages/zend-loader/library/Zend/Loader.php:134
/home/travis/build/zf1s/zf1/packages/zend-loader/library/Zend/Loader.php:134
/home/travis/build/zf1s/zf1/packages/zend-loader/library/Zend/Loader.php:82
/home/travis/build/zf1s/zf1/packages/zend-validate/library/Zend/Validate/Barcode.php:137
/home/travis/build/zf1s/zf1/packages/zend-validate/library/Zend/Validate/Barcode.php:107
/home/travis/build/zf1s/zf1/tests/Zend/Validate/BarcodeTest.php:345
```

**Comment by marcing** [comment]
It would pass if the file was renamed like I proposed initially. @falkenhawk

**Comment by glensc** [comment]
@marcing you mean class rename, not file rename?

**Comment by marcing** [comment]
Yes I think the class should be renamed, because the adapter loading forces strtolower + ucfirst and the classname change won't work @glensc

**Review by falkenhawk — APPROVED** [review]

**Pull request merged**
