### PR TITLE
Use staabm/annotate-pull-request-from-checkstyle to report violatons in GitHub

### PR DESCRIPTION
**Pull request by glensc**
Requires:
- [x] https://github.com/staabm/annotate-pull-request-from-checkstyle/pull/65
- [x] https://github.com/php-parallel-lint/PHP-Parallel-Lint/pull/51

----

image

### CODE REVIEW

**Comment by glensc** [comment]
php-parallel-lint 1.3 was released:
- https://github.com/php-parallel-lint/PHP-Parallel-Lint/issues/56

so can update to use actual version, rather a branch

**Comment by glensc** [comment]
@falkenhawk ready now

**Comment by glensc** [comment]
The xml errors are weird, nothing has changed in zf1s yet rebuild fails:
- https://github.com/zf1s/zf1/pull/66/checks?check_run_id=2291144070

perhaps setup-php broke php-xml?

**Review by falkenhawk — COMMENTED** [review]
Since the tests failing are not caused by the changes in this PR (I re-ran the workflow on master https://github.com/zf1s/zf1/actions/runs/679790082), I will go ahead and merge this

**Pull request merged**
